# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1366, 768)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(850, 10, 501, 80))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.path_to_image = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.path_to_image.setObjectName("path_to_image")
        self.gridLayout_2.addWidget(self.path_to_image, 0, 1, 1, 1)
        self.btn_choise_image = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btn_choise_image.setObjectName("btn_choise_image")
        self.gridLayout_2.addWidget(self.btn_choise_image, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.histogram = QtWidgets.QLabel(self.centralwidget)
        self.histogram.setGeometry(QtCore.QRect(720, 240, 640, 480))
        self.histogram.setFrameShape(QtWidgets.QFrame.Box)
        self.histogram.setObjectName("histogram")
        self.segmented_image = QtWidgets.QLabel(self.centralwidget)
        self.segmented_image.setGeometry(QtCore.QRect(20, 370, 350, 350))
        self.segmented_image.setFrameShape(QtWidgets.QFrame.Box)
        self.segmented_image.setObjectName("segmented_image")
        self.input_image = QtWidgets.QLabel(self.centralwidget)
        self.input_image.setGeometry(QtCore.QRect(20, 10, 350, 350))
        self.input_image.setFrameShape(QtWidgets.QFrame.Box)
        self.input_image.setObjectName("input_image")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1366, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.path_to_image.setText(_translate("MainWindow", "C:\\_Programming\\_DataSets\\for segment\\F0000005.png"))
        self.btn_choise_image.setText(_translate("MainWindow", "Выбрать"))
        self.label.setText(_translate("MainWindow", "Путь к изображению:"))
        self.histogram.setText(_translate("MainWindow", "Histogram"))
        self.segmented_image.setText(_translate("MainWindow", "segmented"))
        self.input_image.setText(_translate("MainWindow", "Input image"))
